### ISSUE TITLE
Put js as the default

### ISSUE THREAD

**Issue by MartinMuzatko** [agirton/webpack-init#1]
Hello! This looks very promising so far.
Could you perhaps use js instead of jsx for the babel loader? As it only makes sense for react apps (or used as standalone)

**Comment by agirton** [comment]
Hi @MartinMuzatko thanks for filing the issue! It will still load `js`, with this current setup it will load `js` and `jsx`. I could certainly make it an option during the selection. Thoughts?

**Comment by MartinMuzatko** [comment]
Oh right! I didn't see the `?` for 0 or 1 of the last character. In that case, it is good as it is.

Thank you a lot for the effort of creating this. This is really great if you get lost into configuration quickly :)
