### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by benavern** [agirton/webpack-init#7]
Hi, I'd like to use your tool but can't figure out what's the problem .

I installed it and ran the commande, here is what I have : 

```
λ webpack-init
? Enter the file name for your webpack config webpack.config.js
? Enter the filename for your entry ./index.js
? Enter the output path, this is where your images and js will be output at ./dist
? Enter the output filename bundle.js
? Is your output in a different directory? Yes
? Enter the path to where you will point to in your index.html e.g. /static/
? What loaders would you like to include?
              Note some loaders may require extra configuration. See
              https://webpack.github.io/docs/list-of-loaders.html  babel,  sass
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

It happens when I select babel & sass loaders then push the enter key.

Could you help me ? 
thank you in advance

**Comment by agirton** [comment]
Hi @benavern thanks for letting me know. Will take a look.

**Comment by agirton** [comment]
Hi @benavern I published a new version to make install a bit more user friendly. Which should give some more visibility into where in the install process this is happening.

Also, what version of Node & NPM are you using? I tested this out on Node 6.7.0 and NPM 3.10.3 and I'm not getting this error.

**Comment by agirton** [comment]
Hi @benavern closing this as I've not heard back in a few weeks as I was unable to replicate. Feel free to reopen, if you have experienced this again.
